/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/categories`; params?: Router.UnknownInputParams; } | { pathname: `/companyProfile`; params?: Router.UnknownInputParams; } | { pathname: `/create-offering-form`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/emphasis`; params?: Router.UnknownInputParams; } | { pathname: `/favoritesPage`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/initial-map`; params?: Router.UnknownInputParams; } | { pathname: `/listage`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/offering-profile`; params?: Router.UnknownInputParams; } | { pathname: `/profile-form`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/vendor-panel`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/categories`; params?: Router.UnknownOutputParams; } | { pathname: `/companyProfile`; params?: Router.UnknownOutputParams; } | { pathname: `/create-offering-form`; params?: Router.UnknownOutputParams; } | { pathname: `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/emphasis`; params?: Router.UnknownOutputParams; } | { pathname: `/favoritesPage`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/initial-map`; params?: Router.UnknownOutputParams; } | { pathname: `/listage`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/offering-profile`; params?: Router.UnknownOutputParams; } | { pathname: `/profile-form`; params?: Router.UnknownOutputParams; } | { pathname: `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/register`; params?: Router.UnknownOutputParams; } | { pathname: `/vendor-panel`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/categories${`?${string}` | `#${string}` | ''}` | `/companyProfile${`?${string}` | `#${string}` | ''}` | `/create-offering-form${`?${string}` | `#${string}` | ''}` | `/dashboard${`?${string}` | `#${string}` | ''}` | `/emphasis${`?${string}` | `#${string}` | ''}` | `/favoritesPage${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/initial-map${`?${string}` | `#${string}` | ''}` | `/listage${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/offering-profile${`?${string}` | `#${string}` | ''}` | `/profile-form${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `/vendor-panel${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/categories`; params?: Router.UnknownInputParams; } | { pathname: `/companyProfile`; params?: Router.UnknownInputParams; } | { pathname: `/create-offering-form`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/emphasis`; params?: Router.UnknownInputParams; } | { pathname: `/favoritesPage`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/initial-map`; params?: Router.UnknownInputParams; } | { pathname: `/listage`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/offering-profile`; params?: Router.UnknownInputParams; } | { pathname: `/profile-form`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/vendor-panel`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
